Importing the Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing the Dataset

In [2]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

Tampilkan x

In [3]:
print(x)

[['Samsung' 100.0 100000.0]
 ['Vivo' 80.0 80000.0]
 ['Xiaomi' 150.0 70000.0]
 ['Vivo' 75.0 90000.0]
 ['Oppo' 90.0 95000.0]
 ['Xiaomi' 115.0 nan]
 ['Samsung' 130.0 110000.0]
 ['Oppo' nan 85000.0]
 ['Xiaomi' 95.0 65000.0]
 ['Vivo' 85.0 85000.0]
 ['Samsung' nan 90000.0]
 ['Oppo' 70.0 95000.0]
 ['Xiaomi' 90.0 100000.0]
 ['Samsung' 110.0 nan]
 ['Vivo' 90.0 80000.0]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No'
 'Yes' 'No']


Splitting the Dataset Into the Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2,  random_state = 0)

Menghilangkan Missing Value (nan)

In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

Tampilkan x

In [7]:
print(x)

[['Samsung' 100.0 100000.0]
 ['Vivo' 80.0 80000.0]
 ['Xiaomi' 150.0 70000.0]
 ['Vivo' 75.0 90000.0]
 ['Oppo' 90.0 95000.0]
 ['Xiaomi' 115.0 88076.92307692308]
 ['Samsung' 130.0 110000.0]
 ['Oppo' 98.46153846153847 85000.0]
 ['Xiaomi' 95.0 65000.0]
 ['Vivo' 85.0 85000.0]
 ['Samsung' 98.46153846153847 90000.0]
 ['Oppo' 70.0 95000.0]
 ['Xiaomi' 90.0 100000.0]
 ['Samsung' 110.0 88076.92307692308]
 ['Vivo' 90.0 80000.0]]


Encoding Data Kategori (Atribut)

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import  OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

Encoding Data Kategori (Class/Label)

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

Tampilkan y

In [10]:
print(y)

[0 1 0 0 1 1 0 1 0 1 0 1 0 1 0]


Membagi Dataset ke Dalam Training set dan test set

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test , y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

Tampilan

In [12]:
print(x_train)

[[0.0 0.0 0.0 1.0 150.0 70000.0]
 [0.0 1.0 0.0 0.0 98.46153846153847 90000.0]
 [1.0 0.0 0.0 0.0 90.0 95000.0]
 [0.0 0.0 1.0 0.0 80.0 80000.0]
 [0.0 1.0 0.0 0.0 110.0 88076.92307692308]
 [0.0 1.0 0.0 0.0 100.0 100000.0]
 [0.0 0.0 1.0 0.0 90.0 80000.0]
 [0.0 0.0 1.0 0.0 85.0 85000.0]
 [0.0 0.0 0.0 1.0 95.0 65000.0]
 [0.0 0.0 0.0 1.0 90.0 100000.0]
 [1.0 0.0 0.0 0.0 70.0 95000.0]
 [0.0 0.0 0.0 1.0 115.0 88076.92307692308]]


In [13]:
print(x_test)

[[0.0 0.0 1.0 0.0 75.0 90000.0]
 [1.0 0.0 0.0 0.0 98.46153846153847 85000.0]
 [0.0 1.0 0.0 0.0 130.0 110000.0]]


In [14]:
print(y_train)

[0 0 1 1 1 0 0 1 0 0 1 1]


In [15]:
print(y_test)

[0 1 0]


Feature Scaling

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

Tampilan

In [17]:
print(x_train)

[[0.0 0.0 0.0 1.4142135623730951 2.661327752622985 -1.5427369619993432]
 [0.0 1.0 0.0 -0.7071067811865475 0.0343080925752501 0.34484708562338284]
 [1.0 0.0 0.0 -0.7071067811865475 -0.39699364265646786 0.8167430975290644]
 [0.0 0.0 1.0 -0.7071067811865475 -0.9067138752030434 -0.5989449381879801]
 [0.0 1.0 0.0 -0.7071067811865475 0.622446822436683 0.16334861950581314]
 [0.0 1.0 0.0 -0.7071067811865475 0.11272658989010759 1.2886391094347458]
 [0.0 0.0 1.0 -0.7071067811865475 -0.39699364265646786
  -0.5989449381879801]
 [0.0 0.0 1.0 -0.7071067811865475 -0.6518537589297556
  -0.12704892628229866]
 [0.0 0.0 0.0 1.4142135623730951 -0.14213352638318014 -2.0146329739050244]
 [0.0 0.0 0.0 1.4142135623730951 -0.39699364265646786 1.2886391094347458]
 [1.0 0.0 0.0 -0.7071067811865475 -1.4164341077496188 0.8167430975290644]
 [0.0 0.0 0.0 1.4142135623730951 0.8773069387099708 0.16334861950581314]]


In [18]:
print(x_test)

[[0.0 0.0 1.0 -0.7071067811865475 -1.161573991476331 0.34484708562338284]
 [1.0 0.0 0.0 -0.7071067811865475 0.0343080925752501 -0.12704892628229866]
 [0.0 1.0 0.0 -0.7071067811865475 1.641887287529834 2.232431133246109]]
